#!/bin/bash
export DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PARENT="$(dirname "${DIR}")"
export NDK="$(dirname "${PARENT}")"
export PATH="$PATH:$NDK"
export PROJECT_JNI="$(dirname "${NDK}")/JNI/app/jni"
export PROJECT_LIBS="$(dirname "${NDK}")/JNI/app/libs"
#export CONFIGURATION="pass here additional configuration flags if you want to"
export ADDI_CFLAGS="-fPIC"
export ADDI_LDFLAGS="-Wl,-z,defs"
export FFMPEG_AUDIO_FLAGS="--enable-demuxer=image2 \
--enable-demuxer=aac \
--enable-demuxer=ac3 \
--enable-demuxer=aiff \
--enable-demuxer=amr \
--enable-demuxer=ape \
--enable-demuxer=asf \
--enable-demuxer=au \
--enable-demuxer=avi \
--enable-demuxer=flac \
--enable-demuxer=flv \
--enable-demuxer=matroska \
--enable-demuxer=mov,mp4,m4a,3gp,3g2,mj2 \
--enable-demuxer=m4v \
--enable-demuxer=mp3 \
--enable-demuxer=mpc \
--enable-demuxer=mpc8 \
--enable-demuxer=ogg \
--enable-demuxer=pcm* \
--enable-demuxer=rm \
--enable-demuxer=shorten \
--enable-demuxer=tak \
--enable-demuxer=tta \
--enable-demuxer=wav \
--enable-demuxer=wv \
--enable-demuxer=xwma \
--enable-decoder=aac \
--enable-decoder=aac_latm \
--enable-decoder=ac3 \
--enable-decoder=alac \
--enable-decoder=als \
--enable-decoder=ape \
--enable-decoder=atrac1 \
--enable-decoder=atrac3 \
--enable-decoder=eac3 \
--enable-decoder=flac \
--enable-decoder=gsm \
--enable-decoder=gsm_ms \
--enable-decoder=mp1 \
--enable-decoder=mp1float \
--enable-decoder=mp2 \
--enable-decoder=mp2float \
--enable-decoder=mp3 \
--enable-decoder=mp3float \
--enable-decoder=mp3adu \
--enable-decoder=mp3adufloat \
--enable-decoder=mp3on4 \
--enable-decoder=mp3on4float \
--enable-decoder=mpc7 \
--enable-decoder=mpc8 \
--enable-decoder=opus \git co
--enable-decoder=ra_144 \
--enable-decoder=ra_288 \
--enable-decoder=ralf \
--enable-decoder=shorten \
--enable-decoder=tak \
--enable-decoder=tta \
--enable-decoder=vorbis \
--enable-decoder=wavpack \
--enable-decoder=wmalossless \
--enable-decoder=wmapro \
--enable-decoder=wmav1 \
--enable-decoder=wmav2 \
--enable-decoder=wmavoice \
--enable-decoder=pcm* \
--enable-parser=aac \
--enable-parser=aac_latm \
--enable-parser=ac3 \
--enable-parser=cook \
--enable-parser=dca \
--enable-parser=flac \
--enable-parser=gsm \
--enable-parser=mlp \
--enable-parser=mpegaudio \
--enable-parser=opus \
--enable-parser=tak \
--enable-parser=vorbis \
--enable-parser=vp3 \
--enable-parser=vp8"
export COMMON="--disable-static --disable-programs --disable-protocols --disable-network --disable-zlib --disable-devices --disable-avdevice --disable-swscale --disable-doc --disable-encoders --disable-muxers --disable-bsfs --disable-filters --disable-decoders --disable-demuxers --disable-parsers --disable-avresample --enable-shared --enable-protocol=file,pipe --enable-pic --enable-small $FFMPEG_AUDIO_FLAGS"
#./build_armeabi-v7a.sh
./build_arm64-v8a.sh
#./build_x86.sh
#./build_x86_64.sh
